
POST http://localhost:5000/campaigns

{
    "name":"Teclado Mecanico",
    "content":"testeproduto",
    "emails":["cliente1@gmail.com"]  
}

###

GET  http://localhost:5000/campaigns/cl92mr3ba6974njid

###
PATCH http://localhost:5000/campaigns/cancel/cl92mr3ba6974njid6ng

###
DELETE http://localhost:5000/campaigns/delete/cl92mr3ba6974njid6ng