
POST http://localhost:5000/campaigns

{
    "name":"Teclado56",
    "content":"testes",
    "emails":["alves@gmail.com"]  
}

###

GET  http://localhost:5000/campaigns/cl6i37jba694mjbecqp0

###
PATCH http://localhost:5000/campaigns/cancel/cl6i37jba694mjbecqp0

###
DELETE http://localhost:5000/campaigns/delete/cl6i37jba694mjbecqp0